version: 2
registries:
  pkg-kiwitcms-eu:
    type: python-index
    replaces-base: false
    url: https://${{ secrets.GEMFURY_PULL_TOKEN }}@pkg.kiwitcms.eu/pypi/

updates:
  - package-ecosystem: pip
    registries: "*"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5
