dist: xenial
language: python
cache: pip
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
install:
  - pip install -U pip
  - pip install -r devel.txt
  # workaround for https://github.com/tomturner/django-tenants/issues/336
  - pip install psycopg2

before_script:
  - psql -c "CREATE USER kiwi WITH PASSWORD 'kiwi' CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE test_project ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';" -U postgres


script:
  - make check

after_success:
  - coveralls

notifications:
  email:
    on_failure: change
    on_success: never
