version: '2'

services:
    db:
        container_name: postgresql_database
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgresql_database_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: test_project
            POSTGRES_USER: kiwi
            POSTGRES_PASSWORD: kiwi

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8888:80
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@kiwitcms.org
            PGADMIN_DEFAULT_PASSWORD: kiwi

volumes:
    postgresql_database_data:
