# Generated by Django 2.2 on 2019-04-28 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tcms_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(on_delete=models.CASCADE,
                                    related_name='tenant_owner',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
