# Generated by Django 2.2.1 on 2019-05-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_tenants', '0002_tenant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
