# Generated by Django 2.1.7 on 2019-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_tenants', '0002_tenant_authorized_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
