# Generated by Django 2.2.1 on 2019-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_tenants', '0003_use_datetime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
