# Generated by Django 5.0.4 on 2024-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcms_tenants", "0005_rename_on_trial_to_public_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="extra_emails",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
    ]
